### ISSUE TITLE
pyflex import error: undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by kangnil** [yufeiwang63/RL-VLM-F#8]
Hi Yufei, thanks for sharing this amazing work. I tried to follow the instructions but got errors about pyflex. Could you please take a look or share a docker when you get a chance? Sorry I saw people ran into the same [issue]( https://github.com/YunzhuLi/PyFleX/issues/8) but found no solution. I installed cudatookit 11.3 from conda and have cuda-11.2 in /usr/local. Thank you so much.

```  
File "/data/kangnil/RL-VLM-F/softgym/softgym/envs/pour_water.py", line 4, in <module>
    import pyflex
ImportError: /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/build/pyflex.cpython-39-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
```
Here's some information for you: compile output, ld_library_path, nvcc version, and pip list

```
(rlvlmf) ?  RL-VLM-F git:(main) ? cd softgym               
(rlvlmf) ?  softgym git:(main) ? . ./prepare_1.0.sh
(rlvlmf) ?  softgym git:(main) ? . ./compile_1.0.sh
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /home/kangnil/miniconda3/envs/rlvlmf (found suitable version "11.3", minimum required is "9.0") 
-- Found PythonInterp: /home/kangnil/miniconda3/envs/rlvlmf/bin/python (found suitable version "3.9.20", minimum required is "3.9") 
-- Found PythonLibs: /home/kangnil/miniconda3/envs/rlvlmf/lib/libpython3.9.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/kangnil/miniconda3/envs/rlvlmf/include (found version "2.10.4")
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/build
[  5%] Building CXX object CMakeFiles/pyflex.dir/pyflex.cpp.o
[ 10%] Building CXX object CMakeFiles/pyflex.dir/imgui.cpp.o
[ 15%] Building CXX object CMakeFiles/pyflex.dir/shadersDemoContext.cpp.o
[ 21%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/aabbtree.cpp.o
[ 26%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/core.cpp.o
[ 31%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/extrude.cpp.o
[ 36%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/maths.cpp.o
[ 42%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/mesh.cpp.o
[ 47%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/perlin.cpp.o
[ 57%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/sdf.cpp.o
[ 57%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/platform.cpp.o
[ 63%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/pfm.cpp.o
[ 68%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/voxelize.cpp.o
[ 78%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/tga.cpp.o
[ 84%] Building CXX object CMakeFiles/pyflex.dir/data/kangnil/RL-VLM-F/softgym/PyFlex/core/png.cpp.o
[ 84%] Building CXX object CMakeFiles/pyflex.dir/opengl/imguiRenderGL.cpp.o
[ 94%] Building CXX object CMakeFiles/pyflex.dir/opengl/shader.cpp.o
[ 94%] Building CXX object CMakeFiles/pyflex.dir/opengl/shadersGL.cpp.o
In file included from /usr/include/c++/9/cassert:44,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/core/quat.h:30,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/core/maths.h:241,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/core/aabbtree.h:31,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/core/aabbtree.cpp:28:
/data/kangnil/RL-VLM-F/softgym/PyFlex/core/aabbtree.cpp: In member function ?void AABBTree::Build()?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/core/aabbtree.cpp:136:22: warning: ?*? in boolean context, suggest ?&&? instead [-Wint-in-bool-context]
  136 |     assert(m_numFaces*3);
      |            ~~~~~~~~~~^~
/data/kangnil/RL-VLM-F/softgym/PyFlex/core/mesh.cpp: In function ?void ExportToObj(const char*, const Mesh&)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/core/mesh.cpp:601:5: warning: this ?if? clause does not guard... [-Wmisleading-indentation]
  601 |     if (!file)
      |     ^~
/data/kangnil/RL-VLM-F/softgym/PyFlex/core/mesh.cpp:604:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ?if?
  604 |  file << "# positions" << endl;
      |  ^~~~
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp: In function ?GLuint LoadTexture(const char*)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp:212:16: warning: converting to non-pointer type ?GLuint? {aka ?unsigned int?} from NULL [-Wconversion-null]
  212 |         return NULL;
      |                ^~~~
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp: In function ?void InitRenderHeadless(const RenderInitOptions&, int, int)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp:3386:25: warning: invalid conversion from ?EGLConfig? {aka ?void*?} to ?void**? [-fpermissive]
 3386 |  g_eglConfig = configs[0];
      |                ~~~~~~~~~^
      |                         |
      |                         EGLConfig {aka void*}
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp:3390:33: warning: invalid conversion from ?EGLContext? {aka ?void*?} to ?void**? [-fpermissive]
 3390 |  g_eglContext = eglCreateContext(
      |                 ~~~~~~~~~~~~~~~~^
      |                                 |
      |                                 EGLContext {aka void*}
 3391 |           g_eglDisplay,
      |           ~~~~~~~~~~~~~          
 3392 |           g_eglConfig,
      |           ~~~~~~~~~~~~           
 3393 |           EGL_NO_CONTEXT,
      |           ~~~~~~~~~~~~~~~        
 3394 |           NULL);
      |           ~~~~~                  
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp:3398:40: warning: invalid conversion from ?EGLSurface? {aka ?void*?} to ?void**? [-fpermissive]
 3398 |  g_eglSurface = eglCreatePbufferSurface(g_eglDisplay, g_eglConfig,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        EGLSurface {aka void*}
 3399 |            eglPBAttribs);
      |            ~~~~~~~~~~~~~                
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp: At global scope:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/shadersGL.cpp:248:13: warning: ?{anonymous}::g_eglDisplay? defined but not used [-Wunused-variable]
  248 | EGLDisplay* g_eglDisplay;
      |             ^~~~~~~~~~~~
In file included from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/pyflex.cpp:1:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/main.cpp: In function ?int GetKeyFromGameControllerButton(SDL_GameControllerButton)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/main.cpp:84:9: warning: case value ?17? not in enumerated type ?SDL_GameControllerButton? [-Wswitch]
   84 |         case SDL_CONTROLLER_BUTTON_RIGHT_TRIGGER: {
      |         ^~~~
In file included from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/scenes.h:30,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/main.cpp:588,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/pyflex.cpp:1:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_cloth.h: In member function ?virtual void SoftgymCloth::Initialize(pybind11::array_t<float>, int)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_cloth.h:63:14: warning: unused variable ?size? [-Wunused-variable]
   63 |          int size = g_buffers->triangles.size();
      |              ^~~~
In file included from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/scenes.h:31,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/main.cpp:588,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/pyflex.cpp:1:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_fluid.h: In member function ?virtual void SoftgymFluid::Initialize(pybind11::array_t<float>, int)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_fluid.h:43:9: warning: unused variable ?surfaceTension? [-Wunused-variable]
   43 |   float surfaceTension = ptr[4];
      |         ^~~~~~~~~~~~~~
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_fluid.h:44:9: warning: unused variable ?adhesion? [-Wunused-variable]
   44 |   float adhesion = ptr[5];
      |         ^~~~~~~~
In file included from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/scenes.h:32,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/main.cpp:588,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/pyflex.cpp:1:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_softbody.h: In member function ?void SoftgymSoftBody::CreateSoftBody(SoftgymSoftBody::Instance, int)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_softbody.h:202:10: warning: unused variable ?createStart? [-Wunused-variable]
  202 |   double createStart = GetSeconds();
      |          ^~~~~~~~~~~
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_softbody.h:222:10: warning: unused variable ?createEnd? [-Wunused-variable]
  222 |   double createEnd = GetSeconds();
      |          ^~~~~~~~~
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_softbody.h:233:10: warning: unused variable ?skinStart? [-Wunused-variable]
  233 |   double skinStart = GetSeconds();
      |          ^~~~~~~~~
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_softbody.h:245:10: warning: unused variable ?skinEnd? [-Wunused-variable]
  245 |   double skinEnd = GetSeconds();
      |          ^~~~~~~
In file included from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/scenes.h:33,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/main.cpp:588,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/pyflex.cpp:1:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_rigid_cloth.h: In member function ?virtual void SoftgymRigidCloth::Initialize(pybind11::array_t<float>, int)?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/softgym_scenes/softgym_rigid_cloth.h:72:60: warning: comparison of integer expressions of different signedness: ?int? and ?uint32_t? {aka ?unsigned int?} [-Wsign-compare]
   72 |             for (int i=int(g_mesh->GetNumVertices()*0.6); i<g_mesh->GetNumVertices(); ++i)
      |                                                           ~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/scenes.h:80,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/main.cpp:588,
                 from /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/pyflex.cpp:1:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/scenes/shapechannels.h: In member function ?void ShapeChannels::Initialize()?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/scenes/shapechannels.h:26:108: warning: ?<<? in boolean context, did you mean ?<? ? [-Wint-in-bool-context]
   26 |    AddBox(Vec3(0.5f, 0.1f, 0.5f), Vec3(0.0f, 0.5f + i*0.5f, 0.0f), Quat(), false, eNvFlexPhaseShapeChannel0<<i);
      |                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~
[100%] Linking CXX shared module pyflex.cpython-39-x86_64-linux-gnu.so
In function ?strncpy?,
    inlined from ?get_exts? at /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/../../external/glad/src/glad.c:752:24,
    inlined from ?find_extensionsGL? at /data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/../../external/glad/src/glad.c:8839:15:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ?__builtin_strncpy? specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |                                  ^
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/../../external/glad/src/glad.c: In function ?find_extensionsGL?:
/data/kangnil/RL-VLM-F/softgym/PyFlex/bindings/opengl/../../external/glad/src/glad.c:748:32: note: length computed here
  748 |             size_t len = strlen(gl_str_tmp);
      |                                ^
[100%] Built target pyflex

```
```
(rlvlmf) ?  RL-VLM-F git:(main) ? echo $LD_LIBRARY_PATH                                                    
/data/kangnil/RL-VLM-F/softgym/PyFlex/external/SDL2-2.0.4/lib/x64:/home/kangnil/miniconda3/envs/rlvlmf/lib64:/home/kangnil/miniconda3/envs/rlvlmf/lib
```
```
(rlvlmf) ?  RL-VLM-F git:(main) ? nvcc --version                                                                                       

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

 ```
(rlvlmf) ?  RL-VLM-F git:(main) ? pip list                 
Package                      Version
---------------------------- ---------------
absl-py                      2.1.0
accelerate                   1.1.1
addict                       2.4.0
aiofiles                     22.1.0
aiosqlite                    0.20.0
altair                       5.5.0
annotated-types              0.7.0
antlr4-python3-runtime       4.9.3
anyio                        3.7.1
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.1
attrs                        24.2.0
babel                        2.16.0
beautifulsoup4               4.12.3
bleach                       6.2.0
blinker                      1.9.0
blis                         1.0.1
braceexpand                  0.1.7
Brotli                       1.0.9
cachetools                   5.5.0
catalogue                    2.0.10
certifi                      2024.8.30
cffi                         1.17.1
cfgv                         3.4.0
chardet                      5.2.0
charset-normalizer           3.3.2
click                        8.1.7
clip                         1.0
cloudpathlib                 0.20.0
cloudpickle                  3.1.0
cmake                        3.26.4
comm                         0.2.2
confection                   0.1.5
contexttimer                 0.3.3
contourpy                    1.3.0
cycler                       0.12.1
cymem                        2.0.10
debugpy                      1.8.9
decorator                    4.4.2
decord                       0.6.0
defusedxml                   0.7.1
deprecation                  2.1.0
diffusers                    0.16.0
distlib                      0.3.9
distro                       1.9.0
easydict                     1.9
einops                       0.8.0
entrypoints                  0.4
etils                        1.5.2
exceptiongroup               1.2.2
executing                    2.1.0
fairscale                    0.4.4
Farama-Notifications         0.0.4
fastjsonschema               2.21.0
filelock                     3.16.1
fonttools                    4.55.0
fqdn                         1.5.1
fsspec                       2024.10.0
ftfy                         6.3.1
future                       1.0.0
gitdb                        4.0.11
GitPython                    3.1.43
glfw                         1.11.2
google-ai-generativelanguage 0.6.10
google-api-core              2.23.0
google-api-python-client     2.154.0
google-auth                  2.36.0
google-auth-httplib2         0.2.0
google-generativeai          0.8.3
googleapis-common-protos     1.66.0
greenlet                     3.1.1
grpcio                       1.68.0
grpcio-status                1.68.0
gym                          0.25.2
gym-notices                  0.0.8
gymnasium                    0.29.1
h11                          0.14.0
h5py                         3.12.1
httpcore                     1.0.7
httplib2                     0.22.0
httpx                        0.28.0
huggingface-hub              0.24.0
hydra-core                   0.11.3
identify                     2.6.3
idna                         3.10
imageio                      2.36.1
imageio-ffmpeg               0.5.1
importlib_metadata           8.5.0
importlib_resources          6.4.5
iopath                       0.1.10
ipykernel                    6.29.5
ipython                      8.18.1
ipython-genutils             0.2.0
ipywidgets                   8.1.5
isoduration                  20.11.0
jedi                         0.19.2
Jinja2                       3.1.4
jiter                        0.8.0
joblib                       1.4.2
json5                        0.10.0
jsonpointer                  3.0.0
jsonschema                   4.23.0
jsonschema-specifications    2024.10.1
jupyter_client               7.4.9
jupyter_core                 5.7.2
jupyter-events               0.10.0
jupyter_packaging            0.12.3
jupyter_server               2.14.2
jupyter_server_fileid        0.9.3
jupyter_server_terminals     0.5.3
jupyter_server_ydoc          0.8.0
jupyter-ydoc                 0.2.5
jupyterlab                   3.6.8
jupyterlab_pygments          0.3.0
jupyterlab_server            2.27.3
jupyterlab_widgets           3.0.13
kaggle                       1.6.17
kiwisolver                   1.4.7
langcodes                    3.5.0
language_data                1.3.0
lazy_loader                  0.4
lxml                         5.3.0
marisa-trie                  1.2.1
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   3.0.2
matplotlib                   3.9.2
matplotlib-inline            0.1.7
mdurl                        0.1.2
mistune                      3.0.2
mkl-fft                      1.3.0
mkl-random                   1.0.2
mkl-service                  2.3.0
moviepy                      2.0.0.dev2
mpmath                       1.3.0
mujoco                       3.1.1
murmurhash                   1.0.11
narwhals                     1.14.3
nbclassic                    1.1.0
nbclient                     0.10.1
nbconvert                    7.16.4
nbformat                     5.10.4
nest-asyncio                 1.6.0
networkx                     3.2.1
nltk                         3.9.1
nodeenv                      1.9.1
notebook                     6.5.7
notebook_shim                0.2.4
numpy                        1.26.0
nvidia-cublas-cu12           12.4.5.8
nvidia-cuda-cupti-cu12       12.4.127
nvidia-cuda-nvrtc-cu12       12.4.127
nvidia-cuda-runtime-cu12     12.4.127
nvidia-cudnn-cu12            9.1.0.70
nvidia-cufft-cu12            11.2.1.3
nvidia-curand-cu12           10.3.5.147
nvidia-cusolver-cu12         11.6.1.9
nvidia-cusparse-cu12         12.3.1.170
nvidia-nccl-cu12             2.21.5
nvidia-nvjitlink-cu12        12.4.127
nvidia-nvtx-cu12             12.4.127
obspy                        1.4.1
omegaconf                    1.4.1
open3d                       0.14.1
openai                       1.55.3
opencv-python-headless       4.5.5.64
opendatasets                 0.1.22
overrides                    7.7.0
packaging                    24.2
pandas                       2.1.4
pandocfilters                1.5.1
parso                        0.8.4
peft                         0.13.2
pexpect                      4.9.0
pillow                       10.4.0
pip                          24.3.1
platformdirs                 4.3.6
plotly                       5.24.1
portalocker                  3.0.0
pre_commit                   4.0.1
preshed                      3.0.9
proglog                      0.1.10
prometheus_client            0.21.0
prompt_toolkit               3.0.48
proto-plus                   1.25.0
protobuf                     5.29.0
psutil                       6.1.0
ptyprocess                   0.7.0
pure_eval                    0.2.3
pyarrow                      18.1.0
pyasn1                       0.6.1
pyasn1_modules               0.4.1
pybind11                     2.10.4
pybind11-global              2.10.4
pycocoevalcap                1.2
pycocotools                  2.0.8
pycparser                    2.21
pydantic                     2.10.2
pydantic_core                2.27.1
pydeck                       0.9.1
pygame                       2.6.1
Pygments                     2.18.0
PyOpenGL                     3.1.7
pyparsing                    3.2.0
pyquaternion                 0.9.9
PySocks                      1.7.1
python-dateutil              2.9.0.post0
python-dotenv                1.0.1
python-json-logger           2.0.7
python-magic                 0.4.27
python-slugify               8.0.4
pytz                         2024.2
PyYAML                       6.0.2
pyyaml_env_tag               0.1
pyzmq                        26.2.0
referencing                  0.35.1
regex                        2024.11.6
requests                     2.32.3
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rich                         13.9.4
rpds-py                      0.21.0
rsa                          4.9
safetensors                  0.4.5
salesforce-lavis             1.0.1
scikit-image                 0.24.0
scikit-learn                 1.5.2
scipy                        1.13.1
Send2Trash                   1.8.3
sentencepiece                0.2.0
setuptools                   69.0.0
shapely                      2.0.6
shellingham                  1.5.4
six                          1.16.0
smart-open                   7.0.5
smmap                        5.0.1
sniffio                      1.3.1
soundfile                    0.12.1
soupsieve                    2.6
spacy                        3.8.2
spacy-legacy                 3.0.12
spacy-loggers                1.0.5
SQLAlchemy                   1.4.54
srsly                        2.4.8
stack-data                   0.6.3
streamlit                    1.40.2
sympy                        1.13.1
tb-nightly                   2.19.0a20241121
tenacity                     9.0.0
tensorboard-data-server      0.7.2
termcolor                    2.5.0
terminado                    0.18.1
text-unidecode               1.3
thinc                        8.3.2
threadpoolctl                3.5.0
tifffile                     2024.8.30
timm                         0.4.12
tinycss2                     1.4.0
tokenizers                   0.13.3
toml                         0.10.2
tomli                        2.2.1
tomlkit                      0.13.2
torch                        1.12.1
torchaudio                   0.12.1
torchvision                  0.13.1
tornado                      6.4.2
tqdm                         4.67.1
traitlets                    5.14.3
transformers                 4.33.2
triton                       3.1.0
typer                        0.14.0
types-python-dateutil        2.9.0.20241003
typing_extensions            4.11.0
tzdata                       2024.2
uri-template                 1.3.0
uritemplate                  4.1.1
urllib3                      2.2.3
virtualenv                   20.28.0
wasabi                       1.1.3
watchdog                     6.0.0
wcwidth                      0.2.13
weasel                       0.4.1
webcolors                    24.11.1
webdataset                   0.2.100
webencodings                 0.5.1
websocket-client             1.8.0
Werkzeug                     3.1.3
wheel                        0.45.1
widgetsnbextension           4.0.13
wrapt                        1.17.0
y-py                         0.6.2
ypy-websocket                0.8.4
zipp                         3.21.0
```

**Comment by kangnil** [comment]
I pulled from nvidia/cudagl:9.2-devel-ubuntu18.04 and successfully installed softgym in python3.6. 
Then I pull from nvidia/cudagl:11.3.1-devel-ubuntu18.04 and did the same thing.
I tried to compile pyflex/compile_1.0.sh as it as (cuda 9 and python 3.6), doesn't work. 
I changed pyflex/compile_1.0.sh to cuda 11.3 and python 3.9, still get this cudasetupargument error. 
```
cd PyFlex/bindings
rm -rf build
mkdir build
cd build
# Seuss 
if [[ $(hostname) = *"compute-0"* ]] || [[ $(hostname) = *"autobot-"* ]] || [[ $(hostname) = *"yertle"* ]]; then
    export CUDA_BIN_PATH=/usr/local/cuda-11.3
fi
cmake -DPYBIND11_PYTHON_VERSION=3.9 ..
make -j
```

```
[100%] Linking CXX shared module pyflex.cpython-39-x86_64-linux-gnu.so
[100%] Built target pyflex
(rlvlmf) root@cd78c9a6448d:/workspace/RL-VLM-F/softgym/PyFlex/bindings/build# python
Python 3.9.20 (main, Oct  3 2024, 07:27:41) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyflex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /workspace/RL-VLM-F/softgym/PyFlex/bindings/build/pyflex.cpython-39-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
```

**Comment by Orion-Zheng** [comment]
Hi Kangni, I also encountered this error when compiling. May I ask how did you solve it? Thank you!

**Comment by kangnil** [comment]
你需要用pyflex吗？不需要的话可以直接全部删掉，用cartpole这种简单点的任务跑这个codebase，pyflex我弄了docker也没配明白

**Comment by Orion-Zheng** [comment]
> 你需要用pyflex吗？不需要的话可以直接全部删掉，用cartpole这种简单点的任务跑这个codebase，pyflex我弄了docker也没配明白
> […](#)

谢谢回复！我后来找到用docker编译softgym的教程了：
https://gist.github.com/garg-aayush/156ec6ddda3d62e2c0ddad00b7e66956

我最后的解决方案是先装一个CUDA 11.3+CuDNN8的环境，如果已有别的环境可以用Environmental Module 管理（注意CUDA 11.3需要GCC10才可以）。然后用RL-VLM-F的文档中的步骤安装conda环境，最后用上述docker教程中的步骤用softgym的docker编译softgym，然后就没有问题啦😃如果有问题欢迎问我！

**Comment by kangnil** [comment]
感谢感谢🙏🏻那我应该是缺了gcc10

**Comment by vlongle** [comment]
FYI, I constantly ran into this problem installing pyflex for softgym and flingbot. The solution is to build pyflex inside the docker container using cuda 9.2. The authors have provided a prebuilt docker image. Then, I use softgym outside of docker (on host machine). My cuda is 12.5. You'd run `. ./prepare_1.0.sh` to link the compiled pyflex to the host env. Hope that helps!
